CREATE TABLE `basic_data_types` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tiny_int_col` tinyint DEFAULT NULL,
  `small_int_col` smallint DEFAULT NULL,
  `medium_int_col` mediumint DEFAULT NULL,
  `int_col` int DEFAULT NULL,
  `big_int_col` bigint DEFAULT NULL,
  `float_col` float(10,2) DEFAULT NULL,
  `double_col` double(20,10) DEFAULT NULL,
  `decimal_col` decimal(30,15) DEFAULT NULL,
  `char_col` char(10) DEFAULT NULL,
  `varchar_col` varchar(255) DEFAULT NULL,
  `tinytext_col` tinytext,
  `text_col` text,
  `mediumtext_col` mediumtext,
  `longtext_col` longtext,
  `binary_col` binary(10) DEFAULT NULL,
  `varbinary_col` varbinary(255) DEFAULT NULL,
  `tinyblob_col` tinyblob,
  `blob_col` blob,
  `mediumblob_col` mediumblob,
  `longblob_col` longblob,
  `date_col` date DEFAULT NULL,
  `time_col` time DEFAULT NULL,
  `datetime_col` datetime DEFAULT NULL,
  `timestamp_col` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci