CREATE TABLE basic_data_types (
  id NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  tiny_int_col NUMBER(3) DEFAULT NULL,
  small_int_col NUMBER(5) DEFAULT NULL,
  medium_int_col NUMBER(7) DEFAULT NULL,
  int_col NUMBER(10) DEFAULT NULL,
  big_int_col NUMBER(19) DEFAULT NULL,
  float_col NUMBER(10,2) DEFAULT NULL,
  double_col NUMBER(20,10) DEFAULT NULL,
  decimal_col NUMBER(30,15) DEFAULT NULL,
  char_col CHAR(10) DEFAULT NULL,
  varchar_col VARCHAR2(255) DEFAULT NULL,
  tinytext_col CLOB,
  text_col CLOB,
  mediumtext_col CLOB,
  longtext_col CLOB,
  binary_col RAW(10) DEFAULT NULL,
  varbinary_col RAW(255) DEFAULT NULL,
  tinyblob_col BLOB,
  blob_col BLOB,
  mediumblob_col BLOB,
  longblob_col BLOB,
  date_col DATE DEFAULT NULL,
  time_col TIMESTAMP DEFAULT NULL,
  datetime_col TIMESTAMP DEFAULT NULL,
  timestamp_col TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (id)
);